"""Translates the workspace folder tree into Blender asset catalogs.

Blender stores catalogs in ``blender_assets.cats.txt`` at the root of an asset
library, one per line:

    <uuid>:<path/with/slashes>:<display name>

Each asset then records a catalog UUID. That indirection is why the UUIDs must
be **derived from the folder id rather than generated**: a random UUID per sync
would orphan every asset's catalog assignment on the next run, silently
resetting the user's organisation every time they hit Refresh.

``uuid5`` over the server's folder id gives the same UUID on every machine and
every sync, for free.
"""

from __future__ import annotations

import os
import uuid
from typing import Dict, Iterable, List, Optional

#: Fixed namespace so catalog UUIDs are reproducible across machines and installs.
#: Never change this — doing so re-homes every catalog in every existing library.
CATALOG_NAMESPACE = uuid.UUID("6f2a1d94-5e3b-4c8a-9f17-2b8d4e6a0c35")

#: Where assets land when their folder is missing or they sit at the workspace root.
UNFILED_NAME = "Unfiled"
UNFILED_UUID = str(uuid.uuid5(CATALOG_NAMESPACE, "__unfiled__"))


def catalog_uuid(folder_id: str) -> str:
    return str(uuid.uuid5(CATALOG_NAMESPACE, folder_id))


def _sanitize(name: str) -> str:
    """Makes a folder name safe for the catalog path component.

    Slashes would fabricate hierarchy that does not exist, and colons are the
    field separator in the catalog file itself.
    """
    cleaned = name.replace("/", "-").replace("\\", "-").replace(":", "-").strip()
    return cleaned or "Untitled"


class CatalogTree:
    """Folder records from the API, resolved into catalog paths."""

    def __init__(self, folders: Iterable[Dict]):
        self._folders: Dict[str, Dict] = {}
        for folder in folders:
            folder_id = folder.get("id")
            if folder_id:
                self._folders[folder_id] = folder

        self._path_cache: Dict[str, str] = {}

    def path_for(self, folder_id: Optional[str]) -> str:
        """Full catalog path for a folder, e.g. ``Environment/Props/Crates``."""
        if not folder_id or folder_id not in self._folders:
            return UNFILED_NAME

        cached = self._path_cache.get(folder_id)
        if cached is not None:
            return cached

        segments: List[str] = []
        cursor: Optional[str] = folder_id
        # Guards against a parent cycle in the data. The server rejects these on
        # write, but a client should not hang on a malformed tree regardless.
        seen: set = set()

        while cursor and cursor in self._folders and cursor not in seen:
            seen.add(cursor)
            folder = self._folders[cursor]
            segments.append(_sanitize(folder.get("name", "Untitled")))
            cursor = folder.get("parentId")

        path = "/".join(reversed(segments)) or UNFILED_NAME
        self._path_cache[folder_id] = path
        return path

    def uuid_for(self, folder_id: Optional[str]) -> str:
        if not folder_id or folder_id not in self._folders:
            return UNFILED_UUID
        return catalog_uuid(folder_id)

    def entries(self) -> List[tuple]:
        """``(uuid, path, display_name)`` for every folder, plus Unfiled."""
        rows = [(UNFILED_UUID, UNFILED_NAME, UNFILED_NAME)]
        for folder_id, folder in self._folders.items():
            rows.append(
                (
                    catalog_uuid(folder_id),
                    self.path_for(folder_id),
                    _sanitize(folder.get("name", "Untitled")),
                )
            )
        # Sorting by path keeps the file stable between syncs, so it only shows
        # up as changed in version control when something actually changed.
        rows.sort(key=lambda row: row[1])
        return rows


def write_catalog_file(path: str, tree: CatalogTree) -> None:
    """Writes ``blender_assets.cats.txt``.

    Written atomically: Blender reads this file whenever the Asset Browser
    refreshes, and catching it half-written shows an empty or corrupt catalog
    list.
    """
    os.makedirs(os.path.dirname(path), exist_ok=True)

    lines = [
        "# This file is generated by the ProjectFlow add-on.",
        "# Edits will be overwritten on the next sync.",
        "",
        "VERSION 1",
        "",
    ]
    for cat_uuid, cat_path, name in tree.entries():
        lines.append(f"{cat_uuid}:{cat_path}:{name}")

    temp_path = f"{path}.tmp"
    with open(temp_path, "w", encoding="utf-8", newline="\n") as handle:
        handle.write("\n".join(lines) + "\n")
    os.replace(temp_path, path)
